/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedStudyModuleIdRouteImport } from './routes/_protected/study/$moduleId'
import { Route as ProtectedFlashcardsModuleIdRouteImport } from './routes/_protected/flashcards/$moduleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStudyModuleIdRoute = ProtectedStudyModuleIdRouteImport.update({
  id: '/study/$moduleId',
  path: '/study/$moduleId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFlashcardsModuleIdRoute =
  ProtectedFlashcardsModuleIdRouteImport.update({
    id: '/flashcards/$moduleId',
    path: '/flashcards/$moduleId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/flashcards/$moduleId': typeof ProtectedFlashcardsModuleIdRoute
  '/study/$moduleId': typeof ProtectedStudyModuleIdRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/flashcards/$moduleId': typeof ProtectedFlashcardsModuleIdRoute
  '/study/$moduleId': typeof ProtectedStudyModuleIdRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/flashcards/$moduleId': typeof ProtectedFlashcardsModuleIdRoute
  '/_protected/study/$moduleId': typeof ProtectedStudyModuleIdRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/flashcards/$moduleId'
    | '/study/$moduleId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/flashcards/$moduleId'
    | '/study/$moduleId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/flashcards/$moduleId'
    | '/_protected/study/$moduleId'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/study/$moduleId': {
      id: '/_protected/study/$moduleId'
      path: '/study/$moduleId'
      fullPath: '/study/$moduleId'
      preLoaderRoute: typeof ProtectedStudyModuleIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/flashcards/$moduleId': {
      id: '/_protected/flashcards/$moduleId'
      path: '/flashcards/$moduleId'
      fullPath: '/flashcards/$moduleId'
      preLoaderRoute: typeof ProtectedFlashcardsModuleIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedFlashcardsModuleIdRoute: typeof ProtectedFlashcardsModuleIdRoute
  ProtectedStudyModuleIdRoute: typeof ProtectedStudyModuleIdRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedFlashcardsModuleIdRoute: ProtectedFlashcardsModuleIdRoute,
  ProtectedStudyModuleIdRoute: ProtectedStudyModuleIdRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
